import { createHash } from "crypto";
import { createServiceClient } from "@/lib/supabase";

/**
 * Agent Workspace auth (Move 3).
 *
 * Each agent holds a long random access token generated by the admin (see
 * scripts note in the schema). The DB stores only its SHA-256 hash, so a DB
 * leak exposes no usable credentials. The client sends the raw token as
 * `Authorization: Bearer <token>`; we hash and look it up. Constant-time
 * comparison is inherent — the hash IS the lookup key, there is nothing to
 * compare byte-by-byte.
 */

export interface AgentRow {
  id: string;
  name: string;
  role: "price_moderator" | "content_editor" | "partner_agent";
  country_code: string | null;
  active: boolean;
  telegram_chat_id: string | null;
}

export function hashToken(token: string): string {
  return createHash("sha256").update(token).digest("hex");
}

/** Returns the agent for a valid Bearer token, or null. Never throws. */
export async function authenticateAgent(authHeader: string | null): Promise<AgentRow | null> {
  try {
    const token = authHeader?.startsWith("Bearer ") ? authHeader.slice(7).trim() : null;
    // Tokens are 48+ chars of hex — anything shorter is not worth a DB hit.
    if (!token || token.length < 32 || token.length > 128) return null;

    const supabase = createServiceClient();
    const { data, error } = await supabase
      .from("agents")
      .select("id,name,role,country_code,active,telegram_chat_id")
      .eq("token_hash", hashToken(token))
      .eq("active", true)
      .maybeSingle();

    if (error || !data) return null;

    // Fire-and-forget presence stamp — WAD (weekly active days) source.
    supabase
      .from("agents")
      .update({ last_seen_at: new Date().toISOString() })
      .eq("id", data.id)
      .then(() => {}, () => {});

    return data as AgentRow;
  } catch {
    return null;
  }
}

/** Server-side owned-analytics write for agent ops events (no client trip). */
export async function logAgentEvent(event: string, props: Record<string, unknown>) {
  try {
    const supabase = createServiceClient();
    await supabase.from("events").insert({ event, props, device: "agent_workspace" });
  } catch {
    /* analytics must never break the action */
  }
}
