export interface Article {
  slug: string;
  titleAr: string;
  titleEn: string;
  descAr: string;
  descEn: string;
  category: string;
  date: string;
  readMins: number;
  icon: string;
}

export const ARTICLES: Article[] = [
  {
    slug: "كيف-تحسب-سعر-الذهب",
    titleAr: "كيف تحسب سعر الذهب بنفسك؟ طريقة الحساب بالجرام والعيار خطوة بخطوة",
    titleEn: "How to Calculate the Gold Price Yourself — Step by Step by Gram and Karat",
    descAr: "المعادلة الأساسية لحساب الذهب بالجرام، تحويل سعر الأونصة، وحساب السعر النهائي مع المصنعية والضريبة عند الشراء والبيع.",
    descEn: "The core formula for pricing gold per gram, converting the ounce price, and the final cost with making charges and VAT when buying or selling.",
    category: "تعليم",
    date: "2026-07-16",
    readMins: 6,
    icon: "🧮",
  },
  {
    slug: "سعر-بيع-وشراء-الذهب",
    titleAr: "الفرق بين سعر بيع وشراء الذهب — ولماذا تخسر عند إعادة البيع؟",
    titleEn: "Gold Buy vs Sell Price — Why You Lose When Reselling",
    descAr: "لماذا يبيعك المحل بسعر أعلى مما يشتري منك؟ مكونات الفجوة بالأرقام، وكيف تقللها من 24% إلى 2%.",
    descEn: "Why shops sell higher than they buy back: the spread's anatomy in numbers, and how to shrink it from 24% to 2%.",
    category: "تعليم",
    date: "2026-07-16",
    readMins: 6,
    icon: "⚖️",
  },
  {
    slug: "سبائك-الذهب",
    titleAr: "سبائك الذهب للمبتدئين — الأوزان والأسعار وكيف تشتري أول سبيكة",
    titleEn: "Gold Bullion for Beginners — Weights, Prices, and Buying Your First Bar",
    descAr: "الأوزان الشائعة من 1 جرام إلى الكيلو، حساب سعر السبيكة وعلاوة السك، وكيف تشتري وتخزن وتبيع بأمان.",
    descEn: "Common weights from 1g to 1kg, bar pricing and premiums, and how to buy, store, and sell safely.",
    category: "استثمار",
    date: "2026-07-16",
    readMins: 7,
    icon: "🪙",
  },
  {
    slug: "مصنعية-الذهب",
    titleAr: "مصنعية الذهب — ما هي؟ ولماذا تختلف؟ وهل تُسترد عند البيع؟",
    titleEn: "Gold Making Charge — What It Is, Why It Varies, and Is It Refundable?",
    descAr: "دليل شامل لمصنعية الذهب: ما هي، لماذا تختلف من محل لآخر، متوسطها في الخليج ومصر، هل تُسترد عند البيع، وكيف توفّر فيها.",
    descEn: "Complete guide to gold making charges: what they are, why they vary, average rates across the Gulf and Egypt, whether they're refundable, and how to save.",
    category: "تعليم",
    date: "2026-06-24",
    readMins: 7,
    icon: "🏷️",
  },
  {
    slug: "توقعات-سعر-الذهب-2026",
    titleAr: "توقعات سعر الذهب 2026 — بعد تجاوز 4000 دولار، ما التالي؟",
    titleEn: "Gold Price Forecast 2026 — Past $4,000, What Comes Next?",
    descAr: "الذهب تجاوز 4400 دولار للأونصة. تحليل محدث لما تبقى من 2026: المحركات، عوامل الضغط، ثلاثة سيناريوهات محسوبة من المستوى الحالي، وكيف تقرأ التوقعات دون أن تُضلّل.",
    descEn: "Gold has passed $4,400/oz. An updated read on the rest of 2026: drivers, pressure points, three scenarios measured from today's level, and how to read forecasts critically.",
    category: "تحليل",
    date: "2026-08-19",
    readMins: 11,
    icon: "🔮",
  },
  {
    slug: "كيف-تشتري-الذهب",
    titleAr: "كيف تشتري الذهب؟ — دليل المبتدئين الشامل",
    titleEn: "How to Buy Gold? — Complete Beginner's Guide",
    descAr: "دليل عملي خطوة بخطوة: أين تشتري في الخليج، ما تتحقق منه، الفرق بين السبائك والمجوهرات، وكيف تتجنب النصب.",
    descEn: "Step-by-step practical guide: where to buy in the Gulf, what to verify, bullion vs jewelry, and how to avoid scams.",
    category: "تعليم",
    date: "2026-04-25",
    readMins: 6,
    icon: "🛒",
  },
  {
    slug: "سعر-الذهب-اليوم",
    titleAr: "سعر الذهب اليوم — عيار 24 و21 و18 بالجرام والأونصة",
    titleEn: "Gold Price Today — 24K, 21K, 18K per Gram & Ounce",
    descAr: "دليلك الشامل لفهم سعر الذهب اليومي: لماذا يتغير، الفرق بين العيارات، وكيف تقرأ السوق للشراء أو البيع.",
    descEn: "Your complete guide to today's gold price: why it moves, karat differences, and how to read the market.",
    category: "تحليل",
    date: "2026-04-18",
    readMins: 7,
    icon: "📈",
  },
  {
    slug: "ما-يؤثر-على-سعر-الذهب",
    titleAr: "ما الذي يؤثر على سعر الذهب؟ — 7 عوامل رئيسية",
    titleEn: "What Affects Gold Price? — 7 Key Factors",
    descAr: "تعرّف على أهم العوامل التي تحرّك سعر الذهب عالمياً، من الفائدة الأمريكية إلى الأزمات الجيوسياسية.",
    descEn: "Discover the main factors that drive gold prices globally, from US interest rates to geopolitical crises.",
    category: "تحليل",
    date: "2026-04-10",
    readMins: 5,
    icon: "📊",
  },
  {
    slug: "الاستثمار-في-الذهب",
    titleAr: "كيف تستثمر في الذهب؟ — دليل المبتدئين",
    titleEn: "How to Invest in Gold? — Beginner's Guide",
    descAr: "دليل شامل لطرق الاستثمار في الذهب: سبائك، مجوهرات، ETF، وعقود الفيوتشر — مع مقارنة بين كل طريقة.",
    descEn: "A complete guide to gold investment methods: bullion, jewelry, ETFs, and futures — with a comparison.",
    category: "استثمار",
    date: "2026-04-08",
    readMins: 7,
    icon: "💰",
  },
  {
    slug: "عيارات-الذهب",
    titleAr: "دليل عيارات الذهب — ما الفرق بين 24 و21 و18؟",
    titleEn: "Gold Karats Guide — Difference Between 24K, 21K, 18K",
    descAr: "شرح مبسط لعيارات الذهب المختلفة وكيف تؤثر على السعر والجودة والاستخدام.",
    descEn: "A simple explanation of gold karats and how they affect price, quality, and use.",
    category: "تعليم",
    date: "2026-04-06",
    readMins: 4,
    icon: "🥇",
  },
  {
    slug: "زكاة-الذهب",
    titleAr: "زكاة الذهب — كيف تحسبها بالطريقة الصحيحة؟",
    titleEn: "Gold Zakat — How to Calculate It Correctly",
    descAr: "شرح تفصيلي لأحكام زكاة الذهب: النصاب، الحول، النسبة، وكيفية الحساب بالأسعار الحالية.",
    descEn: "Detailed explanation of gold zakat rules: nisab, hawl, rate, and how to calculate with current prices.",
    category: "إسلامي",
    date: "2026-04-04",
    readMins: 6,
    icon: "☪️",
  },
  {
    slug: "سعر-الفضة-اليوم",
    titleAr: "سعر الفضة اليوم — عيار 999 و925 بالجرام والأونصة",
    titleEn: "Silver Price Today — 999 & 925 per Gram & Ounce",
    descAr: "سعر الفضة اليوم بالدولار والريال والدرهم — مع مقارنة بالذهب ونسبة GSR ونصائح الاستثمار والزكاة.",
    descEn: "Today's silver price in USD and Arab currencies — with gold comparison, GSR ratio, investment tips, and zakat rules.",
    category: "استثمار",
    date: "2026-05-10",
    readMins: 7,
    icon: "🪙",
  },
  {
    slug: "تاريخ-سعر-الذهب",
    titleAr: "تاريخ سعر الذهب — من 35 دولاراً إلى 3000+ دولار",
    titleEn: "Gold Price History — From $35 to $3,000+",
    descAr: "رحلة تاريخية لسعر الذهب من بريتون وودز حتى اليوم: صدمة نيكسون، أزمة 2008، كوفيد، و5 دروس للمستثمر.",
    descEn: "Gold price journey from Bretton Woods to today: Nixon Shock, 2008 crisis, COVID, and 5 key investor lessons.",
    category: "تحليل",
    date: "2026-05-10",
    readMins: 8,
    icon: "📜",
  },
  {
    slug: "زكاة-الكريبتو",
    titleAr: "زكاة العملات الرقمية — أحكامها وكيفية حسابها (دليل 2026)",
    titleEn: "Crypto Zakat — Rules, Calculation & Scholarly Opinions (2026 Guide)",
    descAr: "هل تجب الزكاة على البيتكوين وBNB وSOL وUSDT؟ الأحكام الفقهية، النصاب، آراء هيئة كبار العلماء، وطريقة الحساب خطوة بخطوة.",
    descEn: "Is Zakat due on Bitcoin, BNB, SOL, and USDT? Rulings, nisab, scholarly opinions, and step-by-step calculation.",
    category: "إسلامي",
    date: "2026-04-17",
    readMins: 8,
    icon: "₿",
  },
];
