export const GOLD_COUNTRIES = [
  {
    slug: "سعر-الذهب-السعودية",
    currency: "SAR",
    nameAr: "المملكة العربية السعودية",
    nameEn: "Saudi Arabia",
    currencyAr: "ريال سعودي",
    currencyEn: "Saudi Riyal",
    flag: "🇸🇦",
    city: "الرياض",
  },
  {
    slug: "سعر-الذهب-الامارات",
    currency: "AED",
    nameAr: "الإمارات العربية المتحدة",
    nameEn: "United Arab Emirates",
    currencyAr: "درهم إماراتي",
    currencyEn: "UAE Dirham",
    flag: "🇦🇪",
    city: "دبي",
  },
  {
    slug: "سعر-الذهب-الكويت",
    currency: "KWD",
    nameAr: "الكويت",
    nameEn: "Kuwait",
    currencyAr: "دينار كويتي",
    currencyEn: "Kuwaiti Dinar",
    flag: "🇰🇼",
    city: "الكويت",
  },
  {
    slug: "سعر-الذهب-مصر",
    currency: "EGP",
    nameAr: "مصر",
    nameEn: "Egypt",
    currencyAr: "جنيه مصري",
    currencyEn: "Egyptian Pound",
    flag: "🇪🇬",
    city: "القاهرة",
  },
  {
    slug: "سعر-الذهب-قطر",
    currency: "QAR",
    nameAr: "قطر",
    nameEn: "Qatar",
    currencyAr: "ريال قطري",
    currencyEn: "Qatari Riyal",
    flag: "🇶🇦",
    city: "الدوحة",
  },
  {
    slug: "سعر-الذهب-البحرين",
    currency: "BHD",
    nameAr: "البحرين",
    nameEn: "Bahrain",
    currencyAr: "دينار بحريني",
    currencyEn: "Bahraini Dinar",
    flag: "🇧🇭",
    city: "المنامة",
  },
] as const;

export type CountryData = (typeof GOLD_COUNTRIES)[number];
