import { createClient } from "@supabase/supabase-js";

export function createServiceClient() {
  // .trim() guards against trailing newlines baked into Vercel env values
  // (bit us before with ONESIGNAL_REST_API_KEY) — an untrimmed key throws
  // an opaque "invalid header value" error deep inside the HTTP client.
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();
  if (!url || !key) throw new Error("Supabase env vars not configured");
  return createClient(url, key, {
    // Next.js patches global fetch() to cache by default, and that patch
    // reaches into supabase-js's internal fetch calls even on routes marked
    // force-dynamic — without this, writes (e.g. approvals) can appear to
    // "not stick" because reads keep serving a cached pre-write response.
    global: { fetch: (input, init) => fetch(input, { ...init, cache: "no-store" }) },
  });
}

export const supabaseSchema = `
-- جدول التنبيهات
CREATE TABLE IF NOT EXISTS alerts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email TEXT NOT NULL,
  asset TEXT NOT NULL CHECK (asset IN ('gold', 'silver', 'bitcoin', 'ethereum')),
  type TEXT NOT NULL CHECK (type IN ('daily', 'price')),
  target_price DECIMAL,
  condition TEXT CHECK (condition IN ('above', 'below')),
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_sent_at TIMESTAMPTZ
);

-- فهرس على الإيميل
CREATE INDEX IF NOT EXISTS alerts_email_idx ON alerts(email);
CREATE INDEX IF NOT EXISTS alerts_active_idx ON alerts(active);

-- جدول تتبع تنبيهات Push المرسلة (يمنع التكرار)
CREATE TABLE IF NOT EXISTS push_log (
  key TEXT PRIMARY KEY,
  sent_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول خطة المحتوى — لوحة الموافقة /sard-control
CREATE TABLE IF NOT EXISTS content_plan (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  post_date DATE NOT NULL,
  slot TEXT NOT NULL CHECK (slot IN ('morning', 'educational', 'engagement')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'skipped', 'published')),
  template_ig TEXT,
  template_fb TEXT,
  topic TEXT,
  countries JSONB,
  ig_caption TEXT,
  fb_post TEXT,
  x_tweet TEXT,
  card_image_url TEXT,
  card_image_url_fb TEXT,
  market_up BOOLEAN,
  market_price NUMERIC,
  notes TEXT,
  design_notes TEXT,
  edited BOOLEAN DEFAULT false,
  approved_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  post_ids JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(post_date, slot)
);

CREATE INDEX IF NOT EXISTS content_plan_date_idx ON content_plan(post_date);
CREATE INDEX IF NOT EXISTS content_plan_status_idx ON content_plan(status);

-- RLS on: only the service_role key (used server-side by the Next.js API routes
-- and the Python cron) can read/write. No policies = anon key gets nothing.
ALTER TABLE content_plan ENABLE ROW LEVEL SECURITY;

-- جدول الأحداث — مصدر الحقيقة الذي نملكه (Move 1: unified analytics dispatcher)
-- Every track.* call fans out to GA4 + Amplitude + this table via /api/collect.
-- No PII: emails are SHA-256 hashed server-side before insert; no raw URLs with
-- query strings. This is the one store that can JOIN user events to agent events.
CREATE TABLE IF NOT EXISTS events (
  id BIGSERIAL PRIMARY KEY,
  event TEXT NOT NULL,
  props JSONB,
  client_id TEXT,          -- GA client_id, so rows reconcile with GA4/Amplitude
  session_id TEXT,
  page_path TEXT,          -- pathname only, never the query string
  country_code TEXT,       -- from Vercel edge geo header, server-set
  device TEXT,             -- 'mobile' | 'desktop', server-derived from UA
  lang TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS events_event_idx ON events(event);
CREATE INDEX IF NOT EXISTS events_created_idx ON events(created_at);
CREATE INDEX IF NOT EXISTS events_client_idx ON events(client_id);

-- RLS on: service_role only, same posture as content_plan. Raw events never
-- reach the anon/client key. 13-month retention is enforced by a scheduled
-- DELETE (see /api/cron or a Supabase cron) — keep this table lean.
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- ═══════════════════════════════════════════════════════════════════════════
-- Move 3: Agent Workspace — agents, tasks, support requests, price overrides.
-- Auth model: each agent gets a long random access token generated by the
-- admin; only its SHA-256 hash is stored (token_hash). The client sends the
-- raw token as a Bearer header to /api/agent/*, which hashes and looks it up.
-- No plaintext secrets in the DB, no shared PINs, all tables RLS-locked to
-- service_role (every access is mediated by our API routes).
-- ═══════════════════════════════════════════════════════════════════════════

-- الوكلاء — مشرفو الأسعار ومحررو المحتوى
CREATE TABLE IF NOT EXISTS agents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('price_moderator', 'content_editor', 'partner_agent')),
  country_code TEXT,               -- price moderators: the market they own
  token_hash TEXT NOT NULL UNIQUE, -- sha256 hex of the access token
  active BOOLEAN DEFAULT true,
  telegram_chat_id TEXT,           -- optional: agent's own Telegram for pings
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ
);

-- مهام الوكلاء — تُنشأ يدويا من المدير أو تلقائيا من cron
CREATE TABLE IF NOT EXISTS agent_tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  agent_id UUID REFERENCES agents(id) ON DELETE CASCADE,
  task_type TEXT NOT NULL CHECK (task_type IN ('price_verify', 'article', 'review', 'other')),
  title TEXT NOT NULL,
  details TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done', 'skipped')),
  due_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS agent_tasks_agent_idx ON agent_tasks(agent_id, status);

-- طلبات المساعدة — تصل للمدير فورا عبر تيليجرام
CREATE TABLE IF NOT EXISTS support_requests (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  agent_id UUID REFERENCES agents(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('price_data', 'technical', 'content', 'payment', 'other')),
  severity TEXT NOT NULL DEFAULT 'normal' CHECK (severity IN ('urgent', 'normal')),
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved')),
  first_response_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS support_requests_status_idx ON support_requests(status, severity);

-- تعديلات الأسعار المحلية — سعر السوق الفعلي (مصنعية/بيع/شراء) بموافقة المدير
CREATE TABLE IF NOT EXISTS price_overrides (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  agent_id UUID REFERENCES agents(id) ON DELETE CASCADE,
  country_code TEXT NOT NULL,
  karat INT NOT NULL CHECK (karat IN (18, 21, 22, 24)),
  field TEXT NOT NULL CHECK (field IN ('buy', 'sell', 'masna3iya')),
  old_value NUMERIC,
  new_value NUMERIC NOT NULL,
  note TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS price_overrides_status_idx ON price_overrides(status, country_code);

ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE price_overrides ENABLE ROW LEVEL SECURITY;
`;
